
global using IInstanceSetSearchDescriptor = F10Y.L0026.T004.IInstanceSetSearchDescriptor;
global using IInstanceSetTypeSearchDescriptor = F10Y.L0026.T004.IInstanceSetTypeSearchDescriptor;
global using IInstanceVarietySearchDescriptor = F10Y.L0026.T004.IInstanceVarietySearchDescriptor;

global using InstanceSetSearchDescriptor = F10Y.L0026.T004.InstanceSetSearchDescriptor;
global using InstanceSetSearchDescriptor_Aggregate = F10Y.L0026.T004.InstanceSetSearchDescriptor_Aggregate;
global using InstanceSetSearchDescriptor_ApplicabilitySearchDescriptor = F10Y.L0026.T004.InstanceSetSearchDescriptor_ApplicabilitySearchDescriptor;
global using InstanceSetSearchDescriptor_DependencySetSearchDescriptor = F10Y.L0026.T004.InstanceSetSearchDescriptor_DependencySetSearchDescriptor;
global using InstanceSetSearchDescriptor_DomainSearchDescriptor = F10Y.L0026.T004.InstanceSetSearchDescriptor_DomainSearchDescriptor;
global using InstanceSetSearchDescriptor_InstanceSetDescriptor = F10Y.L0026.T004.InstanceSetSearchDescriptor_InstanceSetDescriptor;
global using InstanceSetSearchDescriptor_InstanceSetTypeSearchDescriptor = F10Y.L0026.T004.InstanceSetSearchDescriptor_InstanceSetTypeSearchDescriptor;
global using InstanceSetSearchDescriptor_InstanceVarietySearchDescriptor = F10Y.L0026.T004.InstanceSetSearchDescriptor_InstanceVarietySearchDescriptor;
global using InstanceSetSearchDescriptor_NetVersionSearchDescriptor = F10Y.L0026.T004.InstanceSetSearchDescriptor_NetVersionSearchDescriptor;
global using InstanceSetSearchDescriptor_OpinionSearchDescriptor = F10Y.L0026.T004.InstanceSetSearchDescriptor_OpinionSearchDescriptor;
global using InstanceSetSearchDescriptor_OrganizationName = F10Y.L0026.T004.InstanceSetSearchDescriptor_OrganizationName;
global using InstanceSetSearchDescriptor_OrganizationSearchDescriptor = F10Y.L0026.T004.InstanceSetSearchDescriptor_OrganizationSearchDescriptor;
global using InstanceSetSearchDescriptor_VisibilitySearchDescriptor = F10Y.L0026.T004.InstanceSetSearchDescriptor_VisibilitySearchDescriptor;
global using InstanceSetTypeSearchDescriptor_Name = F10Y.L0026.T004.InstanceSetTypeSearchDescriptor_Name;
global using InstanceVarietySearchDescriptor_Name = F10Y.L0026.T004.InstanceVarietySearchDescriptor_Name;
global using InstanceVarietySearchDescriptor_Values = F10Y.L0026.T004.InstanceVarietySearchDescriptor_Values;

global using N001_InstanceSetSearchDescriptor_Aggregate = F10Y.L0026.T004.N001.InstanceSetSearchDescriptor_Aggregate;
global using N002_InstanceSetSearchDescriptor_Aggregate = F10Y.L0026.T004.N002.InstanceSetSearchDescriptor_Aggregate;

global using N001_Serialization_InstanceSetSearchDescriptor_Aggregate = F10Y.L0026.T004.N001.Serialization.InstanceSetSearchDescriptor_Aggregate;
global using N002_Serialization_InstanceSetSearchDescriptor_Aggregate = F10Y.L0026.T004.N002.Serialization.InstanceSetSearchDescriptor_Aggregate;

global using Serialization_InstanceSetSearchDescriptor = F10Y.L0026.T004.Serialization.InstanceSetSearchDescriptor;
global using Serialization_InstanceSetSearchDescriptor_Aggregate = F10Y.L0026.T004.Serialization.InstanceSetSearchDescriptor_Aggregate;
global using Serialization_InstanceSetSearchDescriptor_ApplicabilitySearchDescriptor = F10Y.L0026.T004.Serialization.InstanceSetSearchDescriptor_ApplicabilitySearchDescriptor;
global using Serialization_InstanceSetSearchDescriptor_DependencySetSearchDescriptor = F10Y.L0026.T004.Serialization.InstanceSetSearchDescriptor_DependencySetSearchDescriptor;
global using Serialization_InstanceSetSearchDescriptor_DomainSearchDescriptor = F10Y.L0026.T004.Serialization.InstanceSetSearchDescriptor_DomainSearchDescriptor;
global using Serialization_InstanceSetSearchDescriptor_InstanceSetTypeSearchDescriptor = F10Y.L0026.T004.Serialization.InstanceSetSearchDescriptor_InstanceSetTypeSearchDescriptor;
global using Serialization_InstanceSetSearchDescriptor_InstanceVarietySearchDescriptor = F10Y.L0026.T004.Serialization.InstanceSetSearchDescriptor_InstanceVarietySearchDescriptor;
global using Serialization_InstanceSetSearchDescriptor_OpinionSearchDescriptor = F10Y.L0026.T004.Serialization.InstanceSetSearchDescriptor_OpinionSearchDescriptor;
global using Serialization_InstanceSetSearchDescriptor_OrganizationSearchDescriptor = F10Y.L0026.T004.Serialization.InstanceSetSearchDescriptor_OrganizationSearchDescriptor;
global using Serialization_InstanceSetTypeSearchDescriptor_Name = F10Y.L0026.T004.Serialization.InstanceSetTypeSearchDescriptor_Name;
global using Serialization_InstanceSetSearchDescriptor_VisibilitySearchDescriptor = F10Y.L0026.T004.Serialization.InstanceSetSearchDescriptor_VisibilitySearchDescriptor;
global using Serialization_InstanceVarietySearchDescriptor_Name = F10Y.L0026.T004.Serialization.InstanceVarietySearchDescriptor_Name;
global using Serialization_InstanceSetSearchDescriptor_NetVersionSearchDescriptor = F10Y.L0026.T004.Serialization.InstanceSetSearchDescriptor_NetVersionSearchDescriptor;
global using Serialization_InstanceVarietySearchDescriptor_Values = F10Y.L0026.T004.Serialization.InstanceVarietySearchDescriptor_Values;
